project:
  type: book
  output-dir: docs/

lang: pt
  
book:
  title: "Ciência de Dados Aplicada à Saúde Materno-Infantil"
  author: "Observatório Obstétrico Brasileiro"
  date: "22/10/2022"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - manipulacao_dados.qmd
    - tabulacao.qmd
    - descritiva.qmd
    - estimacao.qmd
    - testes_np.qmd
    - supervisionada.qmd
    - intro_e_PCA.qmd
  appendices: 
    - href: tutorialr.qmd
      text: Tutorial de R
    - href: references.qmd
      text: Referências 
  
bibliography: references.bib
   
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  pdf:
    documentclass: scrreprt

editor: visual

